######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 26 18:22:43 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

OBJECTS_DIR = .obj
MOC_DIR = .moc

# Input
SOURCES += main.cpp Model.cpp ModelThread.cpp
HEADERS += Model.h ModelThread.h
CONFIG -= app_bundle
